title: Joining the open-source community
author: David Faulkner
email: davidfaulkner350@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A short blog about my joining the open-source community by learning how to use GitHub effectively.
theme: minima

# social links
github_username:  davidfaulkner1 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
